auth_app/urls.py
from django.urls import path
from .views import *

app_name='auth_app'


urlpatterns = [
    path('signup',signUp,name="signup"),
    path('login', loginUser,name="login"),
    path('logout', logoutUser,name="logout"),
    path('updateProfil/',updateUser,name="update_user"),
    path('updatePwd/',updatePwd,name="update_pwd"),
    path('delete/',deleteUser,name="delete_user"),
    path('profil',profilUser,name="profil_user")
]

project_test/urls.py
from ast import pattern
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name='main_app'


urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls,name='admin'),
    path('auth/',include('auth_app.urls')),
    path('',include('food_app.urls')),
    path('like/',include('likeNcom_app.urls'))
]


urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(upload_to='profile_pict',blank=True,null=True)
    
    

    def __str__(self):
        return self.username

auth_app/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import SetPasswordForm

from django.contrib.auth.forms import UserCreationForm

from .models import User



class UserLoginForm(ModelForm):
    username = forms.CharField(required=True)
    
    class Meta:
        model = User 
        fields = ['username','password']
        widgets={
            'password':forms.PasswordInput()
        }
                
        


class UserSignUpForm(UserCreationForm):
    
    
    class Meta:
        first_name = forms.CharField(required=True)
        last_name = forms.CharField(required=True)
        email = forms.EmailField(required=True, max_length=100)
        password = forms.CharField(label='Password', widget=forms.PasswordInput)
        password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)
        model = User 
        fields = ['username','first_name','last_name','email','avatar']
        widgets = {
            'password': forms.PasswordInput(),
        }
        
       
       
class UserUpdateForm(ModelForm):
    
    
    class Meta:
        first_name = forms.CharField(required=True)
        last_name = forms.CharField(required=True)
        email = forms.EmailField(required=True, max_length=100)
        password = forms.CharField(label=("Password"),
        help_text=("Raw passwords are not stored, so there is no way to see "
                    "this user's password, but yeretertertertertretertou can change the password "
                    "using <a href=\"../password/\">this form</a>."))

        model = User 
        fields = ['username','first_name','last_name','email','avatar',]
        
        
        



class PasswordChangeForm(SetPasswordForm):
    pass

auth_app/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import authenticate,login,logout
from .forms import PasswordChangeForm, UserLoginForm, UserSignUpForm, UserUpdateForm
from django.contrib import messages
from .templates import *
from .models import User



def signUp(request):
        if request.method == "POST" :
            form = UserSignUpForm(request.POST,request.FILES)
            if form.is_valid():
                user= form.save(commit=False)
                user.save()
                login(request, user)
                return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
        if request.method == "GET":
            form = UserSignUpForm()
        return render(request,'auth_app/signUp.html',{'form':form})


def loginUser(request):
    if request.method == "POST" :
        username = request.POST['username']
        password = request.POST['password']
        print(username)
        print(password)
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None and user.is_active:
                login(request, user)
                messages.success(request, f"{user.username} connecté")
                context={
                "User":user,
                }
                return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL,context)
        else:
                context={
                "form":UserLoginForm(),
               
                }
                messages.error(request, "Mauvais identifiant/mdp")
                return render(request,"auth_app/login.html",context) 
    if request.method == "GET" : 
            form = UserLoginForm()
    return render(request,"auth_app/login.html",{'form':form}) 
            
    

def logoutUser(request):
        logout(request)
        return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)



def updateUser(request):
        if request.method == "POST":
                  form = UserUpdateForm(request.POST,request.FILES, instance=request.user)
                  if form.is_valid():
                    user = form.save()
                    login(request,user)
                    return HttpResponseRedirect("/auth/profil")
        if request.method == "GET":
                form = UserUpdateForm(instance=request.user)   
        return render(request, 'auth_app/updateProfil.html',{"form":form})
    


def updatePwd(request):
        user = User.objects.get(pk=request.user.id)
        if request.method == "POST":
                  form = PasswordChangeForm(user,request.POST)
                  if form.is_valid():
                    print(form.is_valid)
                    form.save()
                    return HttpResponseRedirect("/auth/profil")
        if request.method == "GET":
                form = PasswordChangeForm(request.user)   
        return render(request, 'auth_app/updatepwd.html',{"form":form})

def deleteUser(request):
    if request.method == "POST" :
                   user = User.objects.get(pk=request.user.id)
                   user.delete()
                   messages.info(request, "compte correctement supprimé")
    return HttpResponseRedirect("/auth/login")




def profilUser(request):
    return render(request, 'auth_app/profilPage.html')
       

auth_app/templates/auth_app/login.html
{% extends "main.html" %} {%block content%} 

  <h1>Test login</h1>

<div class="loginPage">
{% if user.is_authenticated %}
    <p>vous ête déja connecté</p>
    <a href="{% url 'auth_app:logout' %}">logout</a>

  {%else%}
    <div>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
          <button type="submit">Connexion</button>
      </form>
  <small>
    <a href="{% url 'auth_app:signup' %}">pas encore inscrit cliquez ici !</a>
  </small>
  </div>
</div>
{% endif %}{%endblock%}

auth_app/templates/auth_app/profilPage.html
{% extends "main.html" %}
{% load static %}
{%block content%}
<h1>Test User<h1>

    {% if user.is_authenticated %}
    <p>Welcome {{ user.username }} !!!</p> 
    <ul>
    <img src="{% static user.avatar%}"/>
    <li>{{user.last_name}}</li> 
    <li>{{user.first_name}}</li> 
    <li>{{user.email}}</li> 
    </ul>
    <a href="{% url 'auth_app:update_user' %}"> modifier son profil</a>
    <a href="{% url 'auth_app:logout' %}">logout</a> 
    <form action="{% url 'auth_app:delete_user' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="supprimer le compte">
            </form>
    {%else%}
    <a href="{% url 'auth_app:login' %}">connecté vous !</a>
    <a href="{% url 'auth_app:signup' %}">pas encore inscrit cliquez ici !</a>
    {% endif %}
{%endblock%}

auth_app/templates/auth_app/signUp.html
{% extends "main.html" %}

{%block content%}
<div class="signupPage">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
     {{ form.as_p }}
        <button type="submit">SUBMIT</button>
    </form>
    <small>
    <a href="{% url 'auth_app:login' %}">déja inscrit connecté vous !</a>
    </small>
  </div>

{%endblock%}

auth_app/templates/auth_app/updateProfil.html
{% extends "main.html" %}

{%block content%}
<div class="updateProfil">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
     {{ form.as_p }}
     <small>
      <a href="{% url 'auth_app:update_pwd' %}">Pour changer votre password c'est ici</a>
    </small>
        <button type="submit">Modifié les information !</button>
    </form>
   
  </div>

{%endblock%}

auth_app/templates/auth_app/updatepwd.html
{% extends "main.html" %}

{%block content%}
<div class="updatepwd">
    <form method="post" >
        {% csrf_token %}
     {{ form.as_p }}
        <button type="submit">Modifié le mdp !</button>
    </form>
    <small>
    </small>
  </div>

{%endblock%}