auth_app/urls.py
from django.urls import path
from .views import *

app_name='auth_app'


urlpatterns = [
    path('signup',signUp,name="signup"),
    path('login', loginUser,name="login"),
    path('logout', logoutUser,name="logout"),
    path('updateProfil/',updateUser,name="update_user"),
    path('updatePwd/',updatePwd,name="update_pwd"),
    path('delete/',deleteUser,name="delete_user"),
    path('profil',profilUser,name="profil_user")
]

food_app/urls.py
from django.urls import path
from .views import *

app_name='food_app'


urlpatterns = [
    path('all',allRestaurants,name="all_restaurants"),
    path('add',addRestaurant,name="add_restaurant"),
    path('one/<int:restaurantId>/',oneRestaurant,name="one_restaurant"),
    path('updateRestaurant/<int:restaurantId>/',updateRestaurant,name="update_restaurant"),
    path('restaurantsOfUser/',restaurantsOfUser,name="restaurantsOfUser"),
    path('deleteRestaurant/<int:restaurantId>/',deleteRestaurant,name='restaurant_delete')
    # path('restaurantsby/<str:food_type>/',restaurantByCateg,name="restaurant_by_food_type")
]

likeNcom_app/urls.py
from django.urls import path
from .views import *

app_name='likeNcom_app'

urlpatterns = [
  path('addOrDeleteLike/<int:restaurantId>/',addOrDeleteLike,name="addOrDelete_like"),
  path('addComment/<int:restaurantId>/',addComment,name="addComment"),
  path('deleteComment/<int:restaurantId>/<int:commentId>/',deleteComment,name="deleteComment")
]

project_test/urls.py
from ast import pattern
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name='main_app'


urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls,name='admin'),
    path('auth/',include('auth_app.urls')),
    path('',include('food_app.urls')),
    path('like/',include('likeNcom_app.urls'))
]


urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_app/models.py
from django.db import models;
from auth_app.models import User



    
    
class Food_type(models.Model):
    name=models.CharField(max_length=150,)
    
    
    
    
    
    def __str__(self):
        return self.name



class Inclusive_type(models.Model):
    name=models.CharField(max_length=150,)
    
    
    
    
    
    def __str__(self):
        return self.name
    
    
    
    
class Restaurant(models.Model):
    name=models.CharField(max_length=150,)
    adress=models.CharField(max_length=150,)
    price=models.FloatField(null=True, blank=True,default=0)
    creator=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    inclusive_type=models.ForeignKey(Inclusive_type,on_delete=models.SET_NULL,null=True)
    food_type=models.ForeignKey(Food_type,on_delete=models.SET_NULL,null=True)
    image = models.ImageField(upload_to='restaurant_pict',blank=True,null=True)
    likes = models.ManyToManyField(User,related_name="restaurant_post",blank=True,default="")

    
    

    def __str__(self):
        return self.name
    

food_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Restaurant

class RestaurantForm(ModelForm):

    
    class Meta:
        model = Restaurant 
        fields = ['name','adress','price','inclusive_type','food_type','image']
        
       
                
class RestaurantUpdateForm(ModelForm):

    
    class Meta:
        model = Restaurant 
        fields = ['name','adress','price','inclusive_type','food_type','image']

food_app/views.py
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from auth_app.models import User
from likeNcom_app.forms import CommentForm
from likeNcom_app.models import Comment
from .forms import RestaurantForm, RestaurantUpdateForm
from .templates import *
from .models import Restaurant

# Create your views here.

def allRestaurants(request):
    allRestaurants = Restaurant.objects.all()
    context={
        "allRestaurants":allRestaurants
    }
    return render(request,'food_app/allRestaurants.html',context)

def oneRestaurant(request,restaurantId):
    user=request.user
    restaurant = Restaurant.objects.get(pk=restaurantId)
    commentaires = Comment.objects.filter(restaurant=restaurant)
    likeStatus = restaurant.likes.filter(id=user.id).exists()
    print(likeStatus)
    form = CommentForm()
    context={
        "restaurant":restaurant,
        "commentaires":commentaires,
        'form':form,
        'like':likeStatus
    }
    return render(request,'food_app/oneRestaurant.html',context)

def restaurantsOfUser(request):
    if request.method == "GET" :
                 restaurants = Restaurant.objects.filter(creator=request.user)
                 context={
                  "restaurantsOfUser":restaurants
                 }
                 return render(request,"food_app/restaurantsOfUser.html",context)


def addRestaurant(request):
    if request.method == "POST" :
                form = RestaurantForm(request.POST,request.FILES)
                if form.is_valid():
                   restaurant = form.save(commit=False)
                   restaurant.creator = request.user
                   restaurant.save()
                   messages.success(request, f"{restaurant.name} bien ajouté")
                   return HttpResponseRedirect("/all") 
    else:
     form = RestaurantForm()
    return render(request,"food_app/addRestaurant.html",{'form':form}) 



def updateRestaurant(request,restaurantId):
        restaurantInit = Restaurant.objects.get(pk=restaurantId)
        if request.method == "POST":
                  
                  form = RestaurantUpdateForm(request.POST,request.FILES, instance=restaurantInit)
                  if form.is_valid():
                   restaurant = form.save()
                   restaurant.creator = request.user
                   restaurant.save()
                  return HttpResponseRedirect("/restaurantsOfUser")
        else :
                form = RestaurantUpdateForm(instance=restaurantInit)   
                context = {
                "form":form
                ,}
                return render(request, 'food_app/updateRestaurant.html', context)
        
        
def deleteRestaurant(request,restaurantId):
    if request.method == "POST" :
                 restaurant = Restaurant.objects.get(pk=restaurantId)
                 if request.user == restaurant.creator :
                   restaurant.delete()
                   messages.info(request, f"{restaurant.name} bien supprimé")
    return HttpResponseRedirect("/restaurantsOfUser")

food_app/templates/food_app/addRestaurant.html
{% extends "main.html" %}
{% load static %}

{%block content%}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">Ajouté un nouveau restaurant</button>
  </form>


{%endblock%}

food_app/templates/food_app/allRestaurants.html
{% extends "main.html" %}
{% load static %}
{%block content%}

{% if user.is_authenticated %}
<a href="{% url 'food_app:restaurantsOfUser' %}"/>voir les restaurants ajouté par {{user.username}}</a>

{%endif%}
<h1>All restaurants<h1>

{% for restaurant in allRestaurants %}
<p>{{restaurant.name}}</p>
<p>{{restaurant.inclusive_type}}</p>
<p>{{restaurant.adress}}</p>

<a href="{% url 'food_app:one_restaurant' restaurant.id %}">Voir plus sur ce restaurant</a>

{% endfor %}

{%endblock%}

food_app/templates/food_app/editRestaurant.html
{% extends "main.html" %}

{%block content%}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">Ajouté un nouveau restaurant</button>
  </form>


{%endblock%}

food_app/templates/food_app/oneRestaurant.html
{% extends "main.html" %}
{% load static %}


{%block content%}


<p>{{restaurant.name}}<p>
<img src="{% static restaurant.image%}"/>
<p>{{restaurant.adress}}<p>
<p>{{restaurant.price}}<p>
<p>{{restaurant.creator}}<p>
<p>{{restaurant.inclusive_type}}<p>
<p>{{restaurant.food_type}}<p>

    <form action="{% url 'likeNcom_app:addOrDelete_like' restaurant.id %}" method="post">
        {% csrf_token %}
    {% if like %}
    <input type="submit" value="unlike">
</form>
    {% else %}
    <input type="submit" value="like">
</form>
    {% endif %}
       
<p>{{restaurant.likes.count}}</p>

{% if commentaires %}

{% for commentaire in commentaires %}
<p>{{commentaire.user.username}}</p>
<p>{{commentaire.content}}</p>
{% if user == commentaire.user %}
<a href="{% url 'likeNcom_app:deleteComment' restaurant.id commentaire.id%}"><button>supprimer ce commentaire</button></a>


{% endif %}

{% endfor %}
{% endif %}


<form method="post" action="{% url 'likeNcom_app:addComment' restaurant.id %}" >
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">Ajouté un commentaire</button>
  </form>


{% comment %} <img src="{% 'restaurant.image' %}" /> {% endcomment %}





{%endblock%}

food_app/templates/food_app/restaurantsOfUser.html
{% extends "main.html" %}
{% load static %}
{%block content%}

<h1>Restaurants ajouté par {{user.username}} <h1>

    {% for restaurant in restaurantsOfUser %}
    <p>{{restaurant.name}}</p>
    <img src="{% static restaurant.image%}"/>
    <p>{{restaurant.inclusive_type}}</p>
    <p>{{restaurant.adress}}</p>


    <form action="{% url 'food_app:restaurant_delete' restaurant.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
        </form>
    
    
    </br>
    <a href="{% url 'food_app:update_restaurant' restaurant.id%}">Modifier ce restaurant</a>

{%endfor%}
<a href="{% url 'food_app:add_restaurant'%}">Ajouté un nouveau restaurant </a>





{%endblock%}

food_app/templates/food_app/updateRestaurant.html
{% extends "main.html" %}
{% load static %}

{%block content%}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">valider les changements</button>
  </form>


{%endblock%}